version: '3.1'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openpharmarest

  backend:
    depends_on:
      - db
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"