version: "3.1"
name: open-pharma-app
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openpharma
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - openpharma

  braise:
    depends_on:
      - database
    build: ./braise
    environment:
      DB_HOST: database
    networks:
      - openpharma

  nuageux:
    depends_on:
      - braise
    build:
      context: ./nuageux
    environment:
      VITE_BACKEND_ADDRESS: http://192.168.1.22
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - openpharma
    ports:
      - "8080:8080"
      - "3000:3000"

networks:
  openpharma:
volumes:
  postgresql:
    external: true
