// FETCH DATAS

export const FETCH_ALL_PHARMACIES = "FETCH_PHARMACIES";
export const FETCH_OPEN_PHARMACIES = "FETCH_OPEN_PHARMACIES";
export const GET_OPH_CURRENT_STATE = "GET_OPH_CURRENT_STATE";

// STATES
export const SET_LOADING_STATE = "SET_LOADING_STATE";
export const SET_IS_LOCATION_PERMISSION_GRANTED =
  "SET_IS_LOCATION_PERMISSION_GRANTED";

// ACTIONS

export const UPDATE_RELATIVE_DISTANCES = "UPDATE_RELATIVE_DISTANCES";
export const APPLY_FILTER = "APPLY_FILTER";
export const UPDATE_PHARMACIES_DISTANCES = "UPDATE_PHARMACIES_DISTANCIES";
export const SET_DISPLAY_MODE = "SET_DISPLAY_MODE";
export const SET_SORT_MODE = "SET_SORT_MODE";
export const SEARCH_PHARMACIES = "SEARCH_PHARMACIES";
export const SEARCH = "SEARCH";
