export const FETCH_ALL_PHARMACIES = "FETCH_PHARMACIES";
export const FETCH_OPEN_PHARMACIES = "FETCH_OPEN_PHARMACIES";
export const UPDATE_RELATIVE_DISTANCES = "UPDATE_RELATIVE_DISTANCES";
export const APPLY_FILTER = "APPLY_FILTER";
