# Generated by Django 4.1.3 on 2022-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('collected_data', models.JSONField()),
                ('mode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tracker_history',
            },
        ),
    ]
