# Generated by Django 4.1.3 on 2022-11-17 14:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=10)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=5)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='Aucune description.', max_length=1000, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, null=True, size=50)),
                ('google_maps_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('pending_review', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pharmacy',
            },
        ),
        migrations.CreateModel(
            name='OpenPharmacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_from', models.DateTimeField(blank=True, null=True)),
                ('open_until', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openPharma.pharmacy')),
            ],
            options={
                'db_table': 'open_pharmacy',
            },
        ),
    ]
