# Generated by Django 4.1.3 on 2022-11-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openpharmacy',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_pharmacies', to='openPharma.pharmacy'),
        ),
    ]
