# Generated by Django 4.1.3 on 2022-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPharma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openpharmacy',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='openpharmacy',
            name='open_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openpharmacy',
            name='open_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
