# Generated by Django 4.1.4 on 2022-12-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openPharma', '0002_alter_openpharmacy_pharmacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['name', 'date_created', 'active']},
        ),
    ]
