# Generated by Django 4.1.3 on 2022-11-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openPharma', '0003_alter_pharmacy_description_alter_pharmacy_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openpharmacy',
            name='day',
        ),
    ]
