# Generated by Django 4.1.3 on 2022-11-17 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPharma', '0004_remove_openpharmacy_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openpharmacy',
            name='open_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='openpharmacy',
            name='open_until',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=5),
        ),
    ]
