# Generated by Django 4.1.3 on 2022-11-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPharma', '0005_alter_openpharmacy_open_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openpharmacy',
            name='open_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openpharmacy',
            name='open_until',
            field=models.DateTimeField(),
        ),
    ]
