name : "Build Nuageux Web Application"
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name : "Setting up node with actions/setup-node@v3"
        uses : actions/setup-node@v3
        with:
          node-version: "16"
      - name : "Installing packages for the nuageux app"
        working-directory: nuageux
        run : |
          npm install
      - name : "building the nuageux app"
        env:
          VITE_BACKEND_ADDRESS: ${{ secrets.VITE_BACKEND_ADDRESS }}
        working-directory: nuageux
        run : |
          npm run build
  create-merge-request:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create merge request
        uses: actions/github-script@v5
        with:
          script: |
            const { data: { number } } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Automerge',
              head: context.ref,
              base: 'main',
            })
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              labels: ['automerge']
            })