name : "Build Nuageux Web Application"
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    environment:
      name: production
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name : "Setting up node with actions/setup-node@v3"
        uses : actions/setup-node@v3
        with:
          node-version: "16"
      - name : "Installing packages for the nuageux app"
        working-directory: nuageux
        run : |
          npm install
      - name : "building the nuageux app"
        env:
          VITE_BACKEND_ADDRESS: ${{ secrets.VITE_BACKEND_ADDRESS }}
        working-directory: nuageux
        run : |
          npm run build      