name: "Fetch currently open pharmacies from pharma-consults"
on: push
jobs:
  build:
    runs-on: "ubuntu-latest"
  steps:
    name : "Setup"
    uses: actions/checkout@v3
    uses: actions/setup-python@v3
    with:
      python-version: "3.9"
    env:
      OPEN_PHARMA_FIREBASE_CREDENTIALS: ${{secrets.OPEN_PHARMA_FIREBASE_CREDENTIALS}}
      OPEN_PHARMA_DATABASE_URL: ${{secrets.OPEN_PHARMA_DATABASE_URL}}
    run: python -c 'import os;print(os.environ)'


