name: "Update pharmacies list file"
on:
    push:
jobs:
    build:
        runs-on: "macos-latest"
        environment: Environnment
        steps:
            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: "Set up Check out"
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: "Install dependencies"
              run: |
                  cd charbon
                  python -m pip install --upgrade pip
                  sudo pip install wheel
                  pip install -r requirements.txt
            - name: "Run script checking for possible update to the pharmacies lsit"
              run: |
                  cd charbon
                  python update_pharmacies_list.py
                  exit_status=$?
                  if [ "${exit_status}" > 0 ];
                  then
                      # echo "exit sucess ${exit_status}"
                      git status
                      git add pharmacies_list.txt
                      git commit -m "Add $exit_status new entries to the pharmacies list"
                      git push
                  else
                      echo "No update required"
                  fi
