name: "Update pharmacies list file"
on:
    push:
    schedule:
        - cron : "0 0 * * 6,0"
jobs:
    build:
        runs-on: "macos-latest"
        environment: Environnment
        steps:
            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: "Set up Check out"
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: "Install dependencies"
              run: |
                  cd charbon
                  python -m pip install --upgrade pip
                  sudo pip install wheel
                  pip install -r requirements.txt
            - name: "Run script checking for possible update to the pharmacies list"
              env:
                  OPEN_PHARMA_FIREBASE_CREDENTIALS: ${{ secrets.OPEN_PHARMA_FIREBASE_CREDENTIALS }}
                  OPEN_PHARMA_DATABASE_URL: ${{ secrets.OPEN_PHARMA_DATABASE_URL }}
              run: |
                  cd charbon
                  python update_pharmacies_list.py
                  value=`cat data.temp` 
                  if [ "${value}" != 0 ];
                  then
                      echo "exit sucess ${value}"
                      git status
                      git add pharmacies_list.txt
                      git commit -m "Add $value new pharmacies to the list"
                      git push
                  else
                      echo "No update required"
                  fi
