name: "Update pharmacies list file"
on:
    push:
jobs:
    build:
        runs-on: "macos-latest"
        environment: Environnment
        steps:
            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: "Set up Check out"
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: "Install dependencies"
              run: |
                  cd charbon
                  python -m pip install --upgrade pip
                  sudo pip install wheel
                  pip install -r requirements.txt
            - name: "Run script checking for possible update to the pharmacies lsit"
              run: |
                  cd charbon
                  ls
                  value=$(python update_pharmacies_list.py 2>&1)
                  echo "::set-output name=bool::$value"
                  if [ value != "False" ]; then
                      echo "I am here"
                      git add ./"pharmacies_list.txt"
                      # git commit -m "Add $value new pharmacies to the list"
                      echo "Add $value new pharmacies to the list"
                  fi

                  git status
